// Consolidated item data for all 6 wellness topics
// Each item links to /learning/item/?id=[id]
var allItems = [

  // ─── SUPPLEMENTS ─────────────────────────────────────────────────────────
  {
    id: "daily-protein-target",
    title: "Daily Protein Target",
    emoji: "🥩",
    topic: "health",
    topicLabel: "Health",
    evidence: "high",
    trend: false,
    sarxPick: true,
    dosage: "0.7–1.0g / lb",
    when: "Daily",
    desc: "Protein is the primary driver of muscle protein synthesis. The evidence-based range is 0.7–1.0g per pound of bodyweight. Higher intakes (up to 1.2g/lb) are safe and may benefit those in a caloric deficit.",
  },
  {
    id: "creatine-monohydrate",
    title: "Creatine Monohydrate",
    emoji: "💪",
    topic: "supplements",
    topicLabel: "Supplements",
    evidence: "high",
    trend: false,
    sarxPick: true,
    dosage: "5g daily",
    when: "Any time",
    desc: "The most-studied supplement in sports science. Builds strength, increases muscle mass, and improves high-intensity performance. Safe for long-term use. No loading phase required — 5g daily is sufficient.",
  },
  {
    id: "magnesium-glycinate",
    title: "Magnesium Glycinate",
    emoji: "🧂",
    topic: "supplements",
    topicLabel: "Supplements",
    evidence: "high",
    trend: false,
    sarxPick: true,
    dosage: "200–400mg",
    when: "Evening",
    desc: "Low magnesium is linked to poor sleep quality, muscle cramps, and elevated stress hormones. Up to 68% of adults are deficient. The glycinate form is well-absorbed and gentle on the stomach.",
  },
  {
    id: "vitamin-d3-k2",
    title: "Vitamin D3 + K2",
    emoji: "☀️",
    topic: "supplements",
    topicLabel: "Supplements",
    evidence: "high",
    trend: false,
    sarxPick: true,
    dosage: "2,000–5,000 IU",
    when: "With fat",
    desc: "Most people are deficient, especially those who work indoors or live in northern climates. D3 raises serum levels; K2 (MK-7 form) directs calcium to bones instead of arterial walls. Always take with a fat-containing meal for absorption.",
  },
  {
    id: "fish-oil",
    title: "Fish Oil (EPA/DHA)",
    emoji: "🐟",
    topic: "supplements",
    topicLabel: "Supplements",
    evidence: "high",
    trend: false,
    sarxPick: true,
    dosage: "2–3g combined",
    when: "With meals",
    desc: "EPA and DHA reduce systemic inflammation, support cardiovascular health, and improve body composition over time. Most people don't get sufficient omega-3s from diet alone. Look for a triglyceride-form fish oil for better absorption.",
  },
  {
    id: "whey-protein",
    title: "Whey Protein",
    emoji: "🥛",
    topic: "supplements",
    topicLabel: "Supplements",
    evidence: "high",
    trend: false,
    sarxPick: false,
    dosage: "20–40g",
    when: "Post-workout",
    desc: "The fastest-digesting complete protein source. Useful when you can't hit protein targets through whole foods. Whole food protein is always preferable when accessible. Whey isolate is preferable for those who are lactose sensitive.",
  },
  {
    id: "zinc-picolinate",
    title: "Zinc Picolinate",
    emoji: "⚡️",
    topic: "supplements",
    topicLabel: "Supplements",
    evidence: "medium",
    trend: false,
    sarxPick: false,
    dosage: "15–30mg",
    when: "Evening",
    desc: "Zinc is involved in testosterone production, immune function, and wound healing. Deficiency is common in athletes who sweat heavily. The picolinate form has meaningfully better absorption than zinc oxide. Don't exceed 40mg — excess zinc blocks copper absorption.",
  },
  {
    id: "ashwagandha",
    title: "Ashwagandha KSM-66",
    emoji: "🌿",
    topic: "supplements",
    topicLabel: "Supplements",
    evidence: "medium",
    trend: false,
    sarxPick: false,
    dosage: "300–600mg",
    when: "Daily",
    desc: "KSM-66 is the most clinically studied ashwagandha extract. Evidence supports cortisol reduction, stress adaptation, and modest strength improvements in resistance training. Effects build over 4–8 weeks — not a fast-acting compound.",
  },
  {
    id: "caffeine",
    title: "Caffeine",
    emoji: "☕️",
    topic: "supplements",
    topicLabel: "Supplements",
    evidence: "high",
    trend: false,
    sarxPick: false,
    dosage: "3–6mg / kg",
    when: "30min pre-workout",
    desc: "One of the most effective and evidence-backed performance enhancers. Improves endurance, power output, and focus. Dose relative to bodyweight for accuracy. Hard cutoff at noon — caffeine's 5–7 hour half-life directly degrades sleep quality if consumed later.",
  },

  // ─── GUT HEALTH ──────────────────────────────────────────────────────────
  {
    id: "gut-health",
    title: "Gut Health",
    emoji: "🥒",
    topic: "health",
    topicLabel: "Health",
    evidence: "high",
    trend: false,
    sarxPick: true,
    dosage: "Daily habits",
    when: "Every meal",
    desc: "The gut microbiome drives immune function, inflammation, mood, and metabolic health. Two levers move it the most: what you add and what you cut.\n\nAdd fermented foods: kimchi, yogurt, kefir, sauerkraut, and kombucha directly seed live bacteria into the gut. A Stanford RCT found daily fermented food intake for 10 weeks significantly increased microbiome diversity and decreased inflammatory markers — outperforming a high-fiber diet alone. 1–2 servings daily is sufficient.\n\nCut ultra-processed foods: UPFs disrupt microbiome composition within days. Emulsifiers like carboxymethylcellulose directly damage the intestinal mucus layer. Artificial sweeteners alter microbial metabolism. Even partial reduction improves markers — aim to keep UPFs under 20% of total calories.",
  },
  {
    id: "apple-cider-vinegar",
    title: "Apple Cider Vinegar",
    emoji: "🥃",
    topic: "health",
    topicLabel: "Health",
    evidence: "trend",
    trend: true,
    sarxPick: false,
    dosage: "1 tbsp",
    when: "Wellness fad",
    desc: "The primary claimed mechanism — alkalizing the gut — doesn't survive contact with stomach acid. The small human studies that exist are underpowered, short-term, and often manufacturer-funded. The raw apple cider version contains trace 'mother' bacteria, but far less than any fermented food.",
  },

  // ─── SLEEP & RECOVERY ────────────────────────────────────────────────────
  {
    id: "circadian-rhythm",
    title: "Circadian Rhythm",
    emoji: "🌓",
    topic: "health",
    topicLabel: "Health",
    evidence: "high",
    trend: false,
    sarxPick: true,
    dosage: "Daily habits",
    when: "Morning & night",
    desc: "Your circadian clock controls sleep onset, cortisol, metabolism, and body temperature. It runs on light, timing, temperature, food, movement, and stress cues — most people's daily habits work against it on multiple fronts.\n\n• Get 7–9 hours: sleep duration is where most deficits accumulate. Even two nights of restriction measurably alters microbiome composition, elevates cortisol, and impairs insulin sensitivity. There is no adaptation to chronic short sleep — you just lose the ability to perceive how impaired you are.\n• Consistent schedule: same bed and wake time within 30 minutes every day, including weekends. Social jetlag on weekends fragments sleep architecture and reduces slow-wave sleep as much as mild deprivation.\n• Morning sunlight: 10 minutes of outdoor light within an hour of waking anchors the clock, triggers the appropriate cortisol spike, and primes melatonin release 14–16 hours later. Overcast sky still delivers 10,000+ lux — window glass blocks the wavelengths that matter.\n• Caffeine cutoff: caffeine has a 5–7 hour half-life. Coffee at 2pm still has half its caffeine active at 9pm, blocking adenosine and reducing slow-wave sleep even when you fall asleep easily. Cut off by noon or at least 8–10 hours before bed.\n• Stop eating 3 hours before bed: digestion raises core body temperature and activates the sympathetic nervous system — the opposite of what sleep onset requires. A 3-hour gap is the evidence-based minimum.\n• No blue light before bed: screens suppress melatonin onset by up to 3 hours. Dim your display and use warm color mode in the hour before sleep — reduced brightness matters more than blue light filters.\n• Pitch-black room: even dim ambient light during sleep suppresses melatonin and elevates next-morning glucose. Blackout curtains or a sleep mask are among the cheapest high-ROI sleep upgrades.\n• Cool bedroom: core temperature must drop 1–3°F to initiate sleep. Keep the room at 65–68°F. A warm shower beforehand paradoxically helps — vasodilation pulls heat away from your core.\n• Daily movement: even 30 minutes of light walking improves sleep onset, depth, and microbiome diversity. Intensity matters less than consistency. Morning or afternoon timing is preferable — vigorous exercise within 2 hours of bed can delay sleep onset.\n• Manage stress: elevated cortisol delays sleep onset and suppresses REM. Brief daily breathwork or mindfulness — even 10 minutes — shows measurable cortisol reduction over 8 weeks. Stress is not just psychological; it directly rewires the sleep architecture.",
  },

  // ─── HYDRATION ───────────────────────────────────────────────────────────
  {
    id: "bodyweight-hydration",
    title: "Daily Water Target",
    emoji: "💧",
    topic: "health",
    topicLabel: "Health",
    evidence: "high",
    trend: false,
    sarxPick: true,
    dosage: "½ oz / lb bodyweight",
    when: "Daily",
    desc: "Half your bodyweight in fluid ounces is a reliable, individualized baseline. At 160 lbs, that's 80 oz (about 10 cups) per day. Adjust upward in heat, at elevation, or with high training volume. This formula scales better than fixed volume recommendations like '8 glasses per day'.\n\nFront-load mornings: you wake up mildly dehydrated after 7–8 hours without water. Plasma volume drops during sleep, affecting blood pressure, cognition, and morning alertness. 16–32 oz first thing restores plasma volume before coffee compounds the mild diuretic effect.\n\nEasiest way to check: urine color. Pale yellow throughout the day means you're on track. Dark yellow or amber means drink more. Clear urine can indicate overhydration — the goal is pale yellow, not clear.\n\nWater-rich foods count: approximately 20% of total daily fluid intake comes from food. Cucumber (96% water), celery (95%), watermelon (92%), and strawberries (91%) contribute meaningfully toward your target. Whole foods hydrate in a way processed foods do not.",
  },
  {
    id: "electrolytes",
    title: "Electrolytes",
    emoji: "🧂",
    topic: "health",
    topicLabel: "Health",
    evidence: "high",
    trend: false,
    sarxPick: false,
    dosage: "1–2g sodium",
    when: "With training",
    desc: "Sodium is the primary electrolyte lost in sweat and the main regulator of fluid distribution. Training without sodium replacement impairs performance and can cause hyponatremia at high volumes. LMNT, table salt in water, or salty foods all work. Potassium and magnesium matter less acutely.",
  },


  // ─── TRAINING ────────────────────────────────────────────────────────────
  {
    id: "progressive-overload",
    title: "Progressive Overload",
    emoji: "📈",
    topic: "health",
    topicLabel: "Health",
    evidence: "high",
    trend: false,
    sarxPick: true,
    dosage: "+2.5–5 lbs",
    when: "Weekly",
    desc: "The foundational principle of all effective training. Without adding stimulus over time — weight, reps, or quality — the body stops adapting. Aim for small consistent increments rather than large occasional jumps.\n\nLog every session: a training log is the mechanism for progressive overload. Without it, you're estimating weights and reps from memory and unconsciously avoiding difficult lifts. A simple notes app with date, exercise, sets, reps, and weight is sufficient. Review it before each session.",
  },
  {
    id: "workout-essentials",
    title: "Workout Essentials",
    emoji: "🏋️",
    topic: "health",
    topicLabel: "Health",
    evidence: "high",
    trend: false,
    sarxPick: true,
    dosage: "Every session",
    when: "Per workout",
    desc: "The variables that actually determine whether training produces results — beyond just showing up.\n\n• Compound movements first: build your program around squat, hip hinge, horizontal push, horizontal pull, and loaded carry. These five patterns recruit the most muscle mass and produce the greatest hormonal response. Isolation work is supplementary.\n• Train each muscle 2x/week: muscle protein synthesis returns to baseline by 72 hours post-training. Twice-weekly frequency keeps the growth window continuously elevated and produces significantly more hypertrophy than once per week at equal volume.\n• Train close to failure: finish each working set with 1–3 reps left in the tank (RIR 1–3). Sets stopped 6+ reps from failure produce a fraction of the growth stimulus. You don't need to go to failure — just close.\n• Weekly volume: 10–20 working sets per muscle per week is the evidence-based hypertrophy range. Start at 10 sets and build up. Volume past your recovery capacity produces inflammation, not adaptation.\n• Rest 2–3 minutes between sets: longer rest allows fuller ATP resynthesis and reduces metabolic fatigue. 2–3 minutes on compound lifts consistently outperforms 60-second rests for both strength and size.\n• Recovery is training: muscle is built during recovery, not during the session. 48 hours minimum between sessions targeting the same muscle group. Sleep and protein intake are the primary levers.\n• Pre-workout hydration: arrive hydrated. Even 2% bodyweight dehydration measurably impairs strength and coordination. 16–20 oz of water 2 hours before training gives kidneys time to process without GI distress during the session.\n• Hydrate during training: drink to thirst for most sessions. For sessions over 60 minutes or in heat, proactive intake of 20–32 oz per hour prevents the performance decline that tracks with dehydration.",
  },

  // ─── FIBER & NUTRITION ───────────────────────────────────────────────────
  {
    id: "daily-fiber-target",
    title: "Daily Fiber Target",
    emoji: "🌾",
    topic: "health",
    topicLabel: "Health",
    evidence: "high",
    trend: false,
    sarxPick: true,
    dosage: "14g / 1,000 kcal",
    when: "Daily",
    desc: "14g of fiber per 1,000 calories consumed is the evidence-based target from the Dietary Guidelines. Most adults eat under 15g total daily. Fiber feeds gut bacteria, slows glucose absorption, reduces LDL cholesterol, and is associated with lower all-cause mortality. Ramp up slowly — no more than 5g per week to avoid GI distress.\n\nTop whole-food sources:\n• Black beans — 15g per cup, plus 15g protein and resistant starch\n• Chia seeds — 10g per 2 tbsp; absorb 12× their weight in water, stabilizing glucose\n• Oats (steel-cut) — 8g per cup; beta-glucan specifically lowers LDL\n• Raspberries — 8g per cup with a low glycemic load; frozen = same nutrition\n• Avocado — 10g per fruit; soluble fiber + oleic acid reduces LDL\n• Broccoli — 5g per cup; also delivers sulforaphane, one of the strongest anti-inflammatory food compounds\n• Apple (with skin) — 4g per fruit; pectin feeds Bifidobacterium — never peel it\n• Almonds — 4g per oz; a portion of the fat is not fully absorbed due to cell wall structure\n\nSkip fiber gummies as a primary source — 3g per serving with none of the polyphenols, resistant starch, or micronutrients of whole foods. Celery juice contains no meaningful fiber at all; the pulp is removed in juicing.",
  },
];
